// <auto-generated />
using System;
using BlazorProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorProject.Migrations
{
    [DbContext(typeof(EiEngsofContext))]
    partial class EiEngsofContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorProject.Data.Models.Anotacao", b =>
                {
                    b.Property<int>("IdAnotacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_anotacao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnotacao"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTime>("DhCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dh_criacao")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DhUltimaEdicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dh_ultima_edicao");

                    b.Property<int?>("IdConsulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    b.Property<int?>("IdUtilizador")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizador");

                    b.HasKey("IdAnotacao")
                        .HasName("pk_anotacao");

                    b.HasIndex(new[] { "IdConsulta" }, "idx_anotacao_consulta");

                    b.HasIndex(new[] { "IdUtilizador" }, "idx_anotacao_utilizador");

                    b.ToTable("anotacao", (string)null);
                });

            modelBuilder.Entity("BlazorProject.Data.Models.CodigoPostal", b =>
                {
                    b.Property<string>("CodPostal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cod_postal");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localidade");

                    b.HasKey("CodPostal")
                        .HasName("pk_codigo_postal");

                    b.ToTable("codigo_postal", (string)null);
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsulta"));

                    b.Property<DateTime?>("DhFim")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dh_fim");

                    b.Property<DateTime>("DhInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dh_inicio");

                    b.Property<int?>("IdExameMedico")
                        .HasColumnType("integer")
                        .HasColumnName("id_exame_medico");

                    b.Property<int?>("IdFatura")
                        .HasColumnType("integer")
                        .HasColumnName("id_fatura");

                    b.Property<int?>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<int?>("IdTipoConsulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_consulta");

                    b.Property<decimal?>("ValorHora")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_hora");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("IdConsulta")
                        .HasName("pk_consulta");

                    b.HasIndex(new[] { "IdExameMedico" }, "idx_consulta_exame");

                    b.HasIndex(new[] { "IdFatura" }, "idx_consulta_fatura");

                    b.HasIndex(new[] { "IdPaciente" }, "idx_consulta_paciente");

                    b.HasIndex(new[] { "IdTipoConsulta" }, "idx_consulta_tipo");

                    b.ToTable("consulta", (string)null);
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("DhRegisto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dh_registo")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EstadoTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estado_to");

                    b.Property<int>("IdConsulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    b.HasKey("IdEstado")
                        .HasName("pk_estado");

                    b.HasIndex(new[] { "IdConsulta" }, "idx_estado_consulta");

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("BlazorProject.Data.Models.ExameMedico", b =>
                {
                    b.Property<int>("IdExameMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_exame_medico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdExameMedico"));

                    b.Property<DateTime>("DhExame")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dh_exame");

                    b.Property<int?>("IdUtilizador")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizador");

                    b.Property<string>("Resultado")
                        .HasColumnType("text")
                        .HasColumnName("resultado");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("IdExameMedico")
                        .HasName("pk_exame_medico");

                    b.HasIndex(new[] { "IdUtilizador" }, "idx_exame_medico_util");

                    b.ToTable("exame_medico", (string)null);
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Fatura", b =>
                {
                    b.Property<int>("IdFatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fatura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFatura"));

                    b.Property<DateTime?>("DhPagamento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dh_pagamento");

                    b.Property<string>("Metodo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metodo");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("IdFatura")
                        .HasName("pk_fatura");

                    b.ToTable("fatura", (string)null);
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("CodPostal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cod_postal");

                    b.Property<DateOnly?>("DtNasc")
                        .HasColumnType("date")
                        .HasColumnName("dt_nasc");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("NumPorta")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("num_porta");

                    b.Property<string>("Rua")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rua");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("IdPaciente")
                        .HasName("pk_paciente");

                    b.HasIndex(new[] { "CodPostal" }, "idx_paciente_codpostal");

                    b.ToTable("paciente", (string)null);
                });

            modelBuilder.Entity("BlazorProject.Data.Models.TipoConsulta", b =>
                {
                    b.Property<int>("IdTipoConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_consulta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoConsulta"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int?>("IdUtilizador")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizador");

                    b.Property<decimal?>("PrecoFixo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_fixo");

                    b.Property<decimal?>("PrecoHora")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_hora");

                    b.HasKey("IdTipoConsulta")
                        .HasName("pk_tipo_consulta");

                    b.HasIndex(new[] { "IdUtilizador" }, "idx_tipo_consulta_util");

                    b.ToTable("tipo_consulta", (string)null);
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Utilizador", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilizador"));

                    b.Property<string>("CodPostal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cod_postal");

                    b.Property<string>("DataHoraAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("DataHoraRegisto")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("especialidade");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsManager")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manager");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("NumCarteira")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("num_carteira");

                    b.Property<string>("NumPorta")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("num_porta");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Rua")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rua");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("IdUtilizador")
                        .HasName("pk_utilizador");

                    b.HasIndex(new[] { "CodPostal" }, "idx_utilizador_codpostal");

                    b.HasIndex(new[] { "Username" }, "utilizador_username_key")
                        .IsUnique();

                    b.ToTable("utilizador", (string)null);
                });

            modelBuilder.Entity("BlazorProject.Data.Models.UtilizadorConsulta", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .HasColumnType("integer")
                        .HasColumnName("id_utilizador");

                    b.Property<int>("IdConsulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    b.Property<bool>("ConviteAceite")
                        .HasColumnType("boolean")
                        .HasColumnName("convite_aceite");

                    b.Property<bool>("IsCriador")
                        .HasColumnType("boolean")
                        .HasColumnName("is_criador");

                    b.HasKey("IdUtilizador", "IdConsulta")
                        .HasName("pk_utilizador_consulta");

                    b.HasIndex("IdConsulta");

                    b.ToTable("utilizador_consulta", (string)null);
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Anotacao", b =>
                {
                    b.HasOne("BlazorProject.Data.Models.Consulta", "IdConsultaNavigation")
                        .WithMany("Anotacaos")
                        .HasForeignKey("IdConsulta")
                        .HasConstraintName("fk_anot_consulta");

                    b.HasOne("BlazorProject.Data.Models.Utilizador", "IdUtilizadorNavigation")
                        .WithMany("Anotacaos")
                        .HasForeignKey("IdUtilizador")
                        .HasConstraintName("fk_anot_utilizador");

                    b.Navigation("IdConsultaNavigation");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Consulta", b =>
                {
                    b.HasOne("BlazorProject.Data.Models.ExameMedico", "IdExameMedicoNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdExameMedico")
                        .HasConstraintName("fk_con_exame");

                    b.HasOne("BlazorProject.Data.Models.Fatura", "IdFaturaNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdFatura")
                        .HasConstraintName("fk_con_fatura");

                    b.HasOne("BlazorProject.Data.Models.Paciente", "IdPacienteNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdPaciente")
                        .HasConstraintName("fk_con_paciente");

                    b.HasOne("BlazorProject.Data.Models.TipoConsulta", "IdTipoConsultaNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdTipoConsulta")
                        .HasConstraintName("fk_con_tipo");

                    b.Navigation("IdExameMedicoNavigation");

                    b.Navigation("IdFaturaNavigation");

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdTipoConsultaNavigation");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Estado", b =>
                {
                    b.HasOne("BlazorProject.Data.Models.Consulta", "IdConsultaNavigation")
                        .WithMany("Estados")
                        .HasForeignKey("IdConsulta")
                        .IsRequired()
                        .HasConstraintName("fk_est_consulta");

                    b.Navigation("IdConsultaNavigation");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.ExameMedico", b =>
                {
                    b.HasOne("BlazorProject.Data.Models.Utilizador", "IdUtilizadorNavigation")
                        .WithMany("ExameMedicos")
                        .HasForeignKey("IdUtilizador")
                        .HasConstraintName("fk_em_utilizador");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Paciente", b =>
                {
                    b.HasOne("BlazorProject.Data.Models.CodigoPostal", "CodPostalNavigation")
                        .WithMany("Pacientes")
                        .HasForeignKey("CodPostal")
                        .HasConstraintName("fk_pac_codpostal");

                    b.Navigation("CodPostalNavigation");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.TipoConsulta", b =>
                {
                    b.HasOne("BlazorProject.Data.Models.Utilizador", "IdUtilizadorNavigation")
                        .WithMany("TipoConsulta")
                        .HasForeignKey("IdUtilizador")
                        .HasConstraintName("fk_tc_utilizador");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Utilizador", b =>
                {
                    b.HasOne("BlazorProject.Data.Models.CodigoPostal", "CodPostalNavigation")
                        .WithMany("Utilizadores")
                        .HasForeignKey("CodPostal")
                        .HasConstraintName("fk_util_codpostal");

                    b.Navigation("CodPostalNavigation");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.UtilizadorConsulta", b =>
                {
                    b.HasOne("BlazorProject.Data.Models.Consulta", "IdConsultaNavigation")
                        .WithMany("UtilizadorConsulta")
                        .HasForeignKey("IdConsulta")
                        .IsRequired()
                        .HasConstraintName("fk_uc_consulta");

                    b.HasOne("BlazorProject.Data.Models.Utilizador", "IdUtilizadorNavigation")
                        .WithMany("UtilizadorConsulta")
                        .HasForeignKey("IdUtilizador")
                        .IsRequired()
                        .HasConstraintName("fk_uc_utilizador");

                    b.Navigation("IdConsultaNavigation");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.CodigoPostal", b =>
                {
                    b.Navigation("Pacientes");

                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Consulta", b =>
                {
                    b.Navigation("Anotacaos");

                    b.Navigation("Estados");

                    b.Navigation("UtilizadorConsulta");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.ExameMedico", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Fatura", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Paciente", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.TipoConsulta", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("BlazorProject.Data.Models.Utilizador", b =>
                {
                    b.Navigation("Anotacaos");

                    b.Navigation("ExameMedicos");

                    b.Navigation("TipoConsulta");

                    b.Navigation("UtilizadorConsulta");
                });
#pragma warning restore 612, 618
        }
    }
}
